title: Bea's notes
author: Bea
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about things.
theme: minima

# social links
github_username:  beatrice93 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
